yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='update_post'),
    path('create/', views.post_create, name='create_post'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.
        as_view(template_name='users/signup.html'),
        name='signup'
    ),
    path(
        'logout/',
        LogoutView
        .as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView
        .as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView
        .as_view(template_name='users/password_change_form.html'),
        name='pass_change_view'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView
        .as_view(template_name='users/password_change_done.html'),
        name='pass_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView
        .as_view(template_name='users/password_reset_form.html'),
        name='pass_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView
        .as_view(template_name='users/password_reset_done.html'),
        name='pass_reset_done'
    ),
    path(
        'reset/<uidb64>/token/',
        PasswordResetConfirmView
        .as_view(template_name='users/password_reset_confirm.html'),
        name='pass_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView
        .as_view(template_name='users/password_reset_complete.html'),
        name='pass_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='auth')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/about/models.py
# from django.db import models

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='Имя страницы')
    description = models.TextField(blank=False, verbose_name='Описание')

    class Meta:
        verbose_name = 'группу'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        blank=False,
        verbose_name='Текст',
        help_text='Введите текст'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Введите название вашей группы'
    )

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'Записи'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[
            'title'
        ] = 'Саша передаёт привет'
        return context


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Технологии'
        context[
            'text'
        ] = 'Гоблинская инженерия!'
        return context

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User


def pagination(posts, request):
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    page_obj = pagination(posts, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = pagination(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = pagination(posts, request)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    context = {
        'form': form,
    }
    if not form.is_valid():
        return render(request, template, context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id, author=request.user)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST or None, instance=post)
    context = {
        'form': form,
        'post': post,
    }
    if form.is_valid():
        form.save()
        return redirect(
            'posts:post_detail', post_id
        )
    return render(request, template, context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import UserCreationForm


class SignUp(CreateView):
    form_class = UserCreationForm
    template_name = 'auth/signup.html'
    success_url = reverse_lazy('posts:index')
    success_message = "Вы успешно зарегистрированы!"

yatube/templates/about/author.html
{% extends "base.html" %}

{% block title %} Об авторе проекта {% endblock %}

{% block content %}
<h1> Привет, я Саня </h1>
<p>
  Простите, я правда торопился
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}

{% block title %} Технологии {% endblock %}

{% block content %}
<div class="row">
  <h1> Вот что я умею </h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p> Ну привет. Неужели остальные разделы настолько скучные, что ты полез сюда? </p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}

<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon"
            sizes="180x180"
            href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon"
            type="image/png"
            sizes="32x32"
            href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon"
            type="image/png"
            sizes="16x16"
            href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
        {% block title %} Контент {% endblock %}
    </title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      {% block content %} Контент {% endblock %}
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>
    © {{ year }} Copyright <span style="color:red">Ya</span>tube
  </p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item"> 
            <a class="nav-link 
              {% if view_name  == 'about:author' %} active {% endif %}"
                href="{% url 'about:author' %}"> Об авторе </a>
          </li>
          <li class="nav-item">
            <a class="nav-link 
              {% if view_name  == 'about:tech' %} active {% endif %}"
                href="{% url 'about:tech' %}"> Технологии </a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link 
                {% if view_name  == 'posts:post_create' %} active {% endif %}"
                  href="{% url 'posts:create_post' %}"> Новая запись </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link 
                {% if view_name  == 'users:password_change' %} active {% endif %}"
                  href="{% url 'users:pass_change_view' %}"> Изменить пароль </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link 
                {% if view_name  == 'users:logout' %} active {% endif %}"
                  href="{% url 'users:logout' %}"> Выйти </a>
            </li>
            <li class="nav-link link-dark">
              Пользователь: <a href="{% url 'posts:profile' user.username %}"> {{ user.username }} </a>
            </li>
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link 
                {% if view_name  == 'auth:login' %} active {% endif %}" 
                  href="{% url 'auth:login' %}"> Войти </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link 
                {% if view_name  == 'auth:signup' %} active {% endif %}" 
                  href="{% url 'auth:signup' %}"> Регистрация </a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">

    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1">
          Первая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}

    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}

  </ul>
</nav>
{% endif %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}
  {% if is_edit %} Сохранить запись {% else %} Добавить запись {% endif %}
{% endblock %}

{% load user_filters %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %} Сохранить запись {% else %} Добавить запись {% endif %}
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data" action=
              {% if is_edit %}
                "{% url 'posts:update_post' post.pk %}"
              {% else %}
                "{% url 'posts:create_post' %}"
              {% endif %}
            >
              {% csrf_token %}
                {% for field in form %}
                  <div class="form-group row my-3 p-3 textarea">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %} {{ group.title }} {% endblock %}

{% block content %}
  <div class="container py-5">
    <h1> {{ group.title }} </h1>
    <h2> {{ group.description|linebreaks }} </h2>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: <a href="{% url 'posts:profile' post.author.username %}"> {{ post.author.username }} </a>
        </li>
        <li> Дата публикации: {{ post.pub_date|date:"d E Y" }} </li>
      </ul>
      <p> {{ post.text|linebreaks }}
        <a href="{% url 'posts:post_detail' post.pk %}"> Детали записи </a>
      </p>
      {% if not forloop.last %} <hr> {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %} Последние обновления на сайте {% endblock %}

{% block content %}
  <div class="container py-5">
    <h1> Последние обновления на сайте </h1>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: <a href="{% url 'posts:profile' post.author.username %}"> {{ post.author.username }} </a>
        </li>
        {% if post.group %}
          <li>
            Группа: <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group.title }} </a>
          </li>
        {% endif %}
        <li> Дата публикации: {{ post.pub_date|date:"d E Y" }} </li>
      </ul>
      <p> {{ post.text|linebreaks }}
        <a href="{% url 'posts:post_detail' post.pk %}"> Детали записи </a>
      </p>
      {% if not forloop.last %} <hr> {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}

{% block title %} Детали записи {% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <li class="list-group-item">
            Автор: <a href="{% url 'posts:profile' post.author.username %}"> {{ post.author.username }} </a>
          </li>
          <li class="list-group-item">
            Всего постов автора: {{ post.author.posts.count }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group.title }} </a>
            </li>
          {% endif %}
        </ul>
      </aside>
      {% if post.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:update_post' post.pk %}">
          Редактировать запись
        </a>
      {% endif %}
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}

{% block title %} Профиль пользователя {{ author.username }} {% endblock %}

{% block content %}
  <div class="container py-5">
    <h1> Все посты пользователя {{ author.username }} </h1>
    <h3> Всего постов: {{ author.posts.count }} </h3>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author.username %}"> {{ post.author.username }} </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}"> Детали записи </a>
      </article>
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}"> Все записи группы {{ group.title }} </a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %} Вы вышли из системы {% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}

{% block title %} Войти {% endblock %}

{% load user_filters %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3"
                  {% if field.field.required %} 
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}
                >
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  <div>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'users:pass_reset' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %} Пароль изменён {% endblock %}

{% block content %}
  <main>
    <div class="container py-5"> 
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Пароль изменён
            </div>
            <div class="card-body"> 
              <p> Пароль изменён успешно </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block title %} Смена пароля {% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            <form method="post" action="users/password_change_form.html">
              <input type="hidden" name="csrfmiddlewaretoken" value="">
              <div class="form-group row my-3 p-3">
                <label for="id_old_password">
                  Старый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul>
                      <li> Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё </li>
                      <li> Ваш пароль должен содержать как минимум 8 символов </li>
                      <li> Ваш пароль не может быть одним из широко распространённых паролей </li>
                      <li> Ваш пароль не может состоять только из цифр </li>
                    </ul>
                  </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Изменить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %} Пароль изменён {% endblock %}

{% block content %}
  <main>
    <div class="container py-5"> 
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Восстановление пароля завершено
            </div>
            <div class="card-body">
              <p> Ваш пароль был сохранен. Используйте его для входа </p>
              <a href="{% url 'users:login' %}"> Войти </a>
            </div> 
          </div> 
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %} Смена пароля {% endblock %}

{% block content %}

{% load user_filters %}

{% if validlink %}
  <main>
    <div class="container py-5"> 
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Введите новый пароль
            </div>
            <div class="card-body">
              <form method="post" action="users/password_reset_confirm.html">
                <input type="hidden" name="csrfmiddlewaretoken" value="">
                <div class="form-group row my-3 p-3">
                  <label for="id_new_password1">
                    Новый пароль
                    <span class="required text-danger">*</span>
                  </label>
                  <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul>
                      <li> Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li>
                      <li> Ваш пароль должен содержать как минимум 8 символов.</li>
                      <li> Ваш пароль не может быть одним из широко распространённых паролей </li>
                      <li> Ваш пароль не может состоять только из цифр </li>
                    </ul>
                  </small>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_new_password2">
                    Подтверждение нового пароля
                    <span class="required text-danger">*</span>
                  </label>
                  <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                </div>
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Назначить новый пароль
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% else %}
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Ошибка
            </div>
            <div class="card-body">
              <p> Ссылка сброса пароля содержит ошибку или устарела </p>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </main>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}

{% block title %} Зарегистрироваться {% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header"> Зарегистрироваться </div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}